name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/santa-erp .
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/santa-erp ${{ secrets.DOCKERHUB_USERNAME }}/santa-erp:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/santa-erp:latest
        
    
